### PR TITLE
Version 2.0.3

### PR DESCRIPTION
**Pull request by varjolintu**
UI has been totally overhauled. Several HTML and JavaScript files have modifications. W3 CSS and Font Awesome added to the project (I know, this increases the size a little bit). There's also a simpler access to options tab and session desctruction. Feel free to test it.

### CODE REVIEW

**Comment by ttyridal** [comment]
Seems someone noticed I'm not a UX guy :) 

This looks like terrific work. I hope to have some time looking into it over the next couple of days

Could one include the icon next to the title, or do you think it should be avoided?

Not to happy about the removal of the copyright / license notice, but I can skip that part. (and you didn't append any attribution to yourself as far as I can see?)

FontAwsome seems to be sil-ofl licensed which, as far as I can understand works well in gpl software.

Finally, it's probably enough with one of the font files, like woff, which seems to be supported by all modern browsers?

**Comment by ttyridal** [comment]
Oh, and would you be OK if I carried your work over to the Firefox incarnation ?

**Comment by ttyridal** [comment]
A couple of points. 

Did you try this on a high-dpi (4k) monitor? The text is **very** small some places. Especially the site name. - Sure enough, type / count is small in the existing design too. It's also hidden by default, as it's "less important information"

The "...." password is now the dominant element in the dialog, previously it was the site name.  IMHO the site name is the most important info in that window, and we want to draw the users attention towards it. Moreover, the site name is user changeable, while the password is not.

There is a bug when clicking the "...." password. Usually it shows the real password, now the whole box disappears.

I really don't like the 'x' for logout. at least to me 'x' conveys close, not logout.

minor: the "verify: xxxxxxx" get a lot more attention than it deserves. There is a big fat red warning if it is anything but expected. It's nice to have, to verify that everything is ok, but it doesn't matter if the users needs to look for it (again, imho)

With an "overhaul", it would be nice if type/generation settings could look somewhat cleaner.. they're still a bit messy i think (size / position)

**Comment by varjolintu** [comment]
Thank you reviewing the build. The licence text removal was a mistake. Now it's back, with the banner icon.

And no, I didn't try this with hdpi monitor. I was afraid the text would be too small so maybe I need to do some more testing and increase the popup size just in case. It would be nice to have an identical UI/UX with any platform, with or without HDPI.

Really good points considering the elements, sizing and the icons. I'll make some improvements and inform when I've made a new commit. Thanks!

**Comment by ttyridal** [comment]
Maybe it's enough to drop the "Password" label, and use approximately that size in the sitename box?

And if white frame suggests user input possible, it may be better to not have it around the password, and then do have it on the user name box.

Just some thoughts...

Oh, and I'll add a copy-to-clipboard button for password in the next version. where it's (with a config option) not copied automatically by default.

**Comment by varjolintu** [comment]
Changes in the latest commit:
- The UI elements are now bigger (both popup and options page)
- Site settings is behind a hide/show button
- Close icon changed to logout icon

I noticed that the original 2.0.2 version and my own were both making an identical behaviour:
1) Click the password field to reveal it
2) Password is shown
3) Click it again -> whole password field is hidden

With the latest commit the password is shown correctly (I assume this is how it should be?).

**Comment by ttyridal** [comment]
Then it's merged.. I reimplemented your gui changes without the w3 style set. It is pixel based and doesn't work so great with varying screen dpi.

Hope I've been true to your changes.

And thanks for the password-show bug fix by the way..

**Comment by varjolintu** [comment]
Looks nice. I also wanted to remove the W3 CSS. Those other improvements were really good too. Keep up the good work :)

**Comment by varjolintu** [comment]
By the way. If you want you can remove my name from the copyright header. Those changes merged were very small after everything you made to the version 2.1.0.

**Comment by ttyridal** [comment]
At the same time, the visual design is your work.

**Pull request merged**
