### PR TITLE
Implement new 'default login names' configuration option, and update …

### PR DESCRIPTION
**Pull request by jmorgannz**
…browser action popup to show a dropdown (cloned from site name dropdown) allowing selection of a default username; but only when the username field is empty (so a new site or one saved with a blank username)

Stop having to enter the same username again and again for each site!

### CODE REVIEW

**Comment by jmorgannz** [comment]
See comment https://github.com/ttyridal/masterpassword-chrome/pull/16#issuecomment-977324181

**Comment by ttyridal** [comment]
Why do you want multiple default names?
Wouldn't that force the user to interact with the field almost as often as having no default?

**Comment by jmorgannz** [comment]
I have several usernames I use around the web - jmorgannz, jmorgan.nz, jmorgan.nz@gmail.com
At the moment every time I visit a new site I have to manually type this in (and then it's saved in the stored site). 
With this patch those options are given to me with a simple click the first time I use MPW on a site, which saves me trying them in. 
It's just a shortcut as I imagine many people would have a similar situation where some websites use an email address, others will use a username - but there would likely only be a handful that cover all cases.

Honestly I really only did it that way because I had the thought whilst implementing it and it was no harder to implement that way for functionality I would definitely use.  

Have you tried using the feature? 
You'll understand if you try it.

**Comment by ttyridal** [comment]
Ok, no, i haven't had the chance to do more than look at it in GitHub. Though I can see it is a useful thing, maybe especially for mobile (?)

**Comment by ttyridal** [comment]
OK,  Tried it and it is actually quite neat :) It might even be better and more intuitive than what I did, where, if you have `inject-user-name` enabled, it would just smack in the default wherever possible.

I could wish for a nicer configuration interface, but I have no immediate constructive feedback on that 😇

And I think the new combobox would work just as well as the old one by the way

**Comment by jmorgannz** [comment]
I thought you might click when you saw it in action :)  
Couple of notes:  

For the config UI: 
-------------------
I figured it's your baby, you likely have ideas on how you want it to look, etc, so did the simplest solution for the config and focussed on functionality fully imagining you might have a better idea on the config side. Personally I like the simplicity of a textarea.

Clear terminology:
--------------------
I originally wrote this using the terminology 'default usernames' (both in code and UI)  
I then realised that this creates ambiguity with the 'master username', where you differentiate the *site* username as a login name; so I refactored the whole thing to refer as 'default login names'.  So there is the MP username, and sites have login names.  
Just wanted to explain the intentional thought there as it easily slips under the radar.

input:change event not firing:
--------------------------------
There is a note about this in the code.  
(ext/src/browser_action/browser_action.js:387)  
I couldn't get the change event handler to fire on #loginname, so had to resort to blur event.
Not sure why, seemed odd - something swallowing the event - but I debugged and looked at attached handlers, and there was nothing untoward.
In any event blur works fine enough.

Happy to port this one over to masterpassword-firefox when I get time.

**Comment by ttyridal** [comment]
hmm.. I'm completely lost when it comes to *creating* user friendly, good looking ui's . What can I say, I'm a back-end guy 🤷  (actually embedded :)) But I know how important it is for adoption :)

regarding input event:  we'll figure that one out over in -firefox .  I think the new combobox is cleaner implemented. at least it's easier to test.

**Pull request closed without merging**
